@host = localhost:8080

// Create Task
POST http://{{host}}/api/tasks HTTP/1.1
content-type: application/json
    
{
    "name": "test-task",
    "description": "random-description",
    "price": 100.00
}

###

// Get Task By ID
GET http://{{host}}/api/tasks/23 HTTP/1.1
content-type: application/json

###

// Get All Tasks
GET http://{{host}}/api/tasks/ HTTP/1.1
content-type: application/json

###

// Update Task
PUT http://{{host}}/api/tasks/23 HTTP/1.1
content-type: application/json

{
    "name": "updated-task",
    "description": "random-description-updated",
    "price": 100.00
}

###

// Delete Task
DELETE http://{{host}}/api/tasks/23 HTTP/1.1
content-type: application/json
    
